version: "3"

volumes:
  db_data:
  solr_data:

services:
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=${SOLA_DB_USER}
      - MYSQL_PASSWORD=${SOLA_DB_PWD}
      - MYSQL_DATABASE=${SOLA_DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      sola_net:

  rabbitmq:
    image: rabbitmq:management
    volumes:
      - ./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      sola_net:

  liresolr:
    image: soruly/liresolr
    volumes:
      - solr_data:/opt/mysolrhome
    ports:
      - "8983:8983"
    networks:
      sola_net:

networks:
  sola_net:
